name = "SpaceDataModel"
uuid = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
version = "0.1.1"
authors = ["Zijin Zhang <zzj956959688@gmail.com>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[compat]
Accessors = "0.1"
julia = "1.10"
